[package]
name = "chessie-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chess = "3.2.0"
chessie = "0.1.0"
# chessie = { path = "../chessie/chessie" }
cozy-chess = "0.3.4"
csv = "1.3.0"
shakmaty = "0.27.2"
